name: Publish Docker Github

on:
  push:
    branches: [main]

jobs:
  publish-etl:
    name: Publish pipeline image (khvostenko/aws-energy-etl)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: khvostenko/aws-energy-etl
          username: khvostenko
          password: ${{ secrets.DOCKER_PASSWORD }}

  publish-viz:
    name: Publish viz image (khvostenko/aws-energy-viz)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: khvostenko/aws-energy-viz
          dockerfile: Dockerfile.viz
          username: khvostenko
          password: ${{ secrets.DOCKER_PASSWORD }}